name: Full Flutter CI

on:
  workflow_dispatch:
    inputs:
      platforms:
        type: string
        default: "windows,macos,linux"

jobs:
  run-ci:
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: false
      platforms: ${{ inputs.platforms }}
